package com.epam.xstack.models.enums;

public enum Code {
    STATUS_200_OK,
    REQUEST_VALIDATION_ERROR,
    STATUS_VALIDATION_ERROR,
    NICKNAME_BUSY,
    INTERNAL_SERVER_ERROR,
    USER_NOT_FOUND,
    USER_NAME_EXISTS,
    USER_NAME_SHOULD_NOT_BE_EMPTY,
    NULL_NOT_ALLOWED,
    AUTHORIZATION_ERROR,
    NOT_SUPPORTED,
    BLOCKED,
    BAD_REQUEST,
    USER_ID_NOT_FOUND
}
